# Generated by Django 3.0.8 on 2020-07-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200704_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='views',
            new_name='show',
        ),
    ]
