# Generated by Django 3.0.8 on 2020-07-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200704_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='email',
        ),
        migrations.RemoveField(
            model_name='news',
            name='picurl',
        ),
    ]
