# Generated by Django 3.0.8 on 2020-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
