# Generated by Django 3.0.8 on 2020-07-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='time',
        ),
    ]
