# Generated by Django 3.0.8 on 2020-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20200707_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
