# Generated by Django 3.0.8 on 2020-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0003_contactform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
