# Generated by Django 3.0.8 on 2020-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0004_auto_20200707_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
