# Generated by Django 3.0.8 on 2020-07-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200703_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='news_detail',
            field=models.TextField(default=''),
        ),
    ]
