# Generated by Django 3.0.8 on 2020-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200706_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='linkedin',
            field=models.CharField(default='-', max_length=60),
        ),
    ]
