# Generated by Django 3.0.8 on 2020-07-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200714_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(blank=True, max_length=12, null=True)),
                ('gender', models.CharField(blank=True, max_length=12, null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('update_on', models.DateField(auto_now_add=True)),
                ('about', models.TextField(blank=True, default='-', null=True)),
            ],
        ),
    ]
