# Generated by Django 3.0.8 on 2020-07-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_register_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_table',
        ),
    ]
