# Generated by Django 3.0.8 on 2020-07-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_register_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname3',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl3',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='main',
            name='picname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='picname2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='picurl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='picurl2',
            field=models.TextField(),
        ),
    ]
