# Generated by Django 3.0.8 on 2020-07-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
