# Generated by Django 3.0.8 on 2020-07-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcat', '0002_auto_20200705_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat',
            name='catid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='catname',
            field=models.CharField(max_length=50),
        ),
    ]
