# Generated by Django 3.0.8 on 2020-07-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='catid',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='catname',
        ),
    ]
