# Generated by Django 3.0.8 on 2020-07-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0002_auto_20200707_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='name',
            new_name='txt',
        ),
    ]
