# Generated by Django 3.0.8 on 2020-07-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200709_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='utxt',
            field=models.TextField(),
        ),
    ]
