# Generated by Django 3.0.8 on 2020-07-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_manager_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='ip',
            field=models.TextField(),
        ),
    ]
